# Generated by Django 5.2.5 on 2025-09-30 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('students', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='students.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
