# Generated by Django 5.2.5 on 2025-09-28 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_options_alter_question_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='questions.question'),
        ),
    ]
