# Generated by Django 5.2.5 on 2025-09-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_alter_questionimage_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4')], max_length=50, null=True)),
                ('category', models.CharField(blank=True, choices=[('Vocabulary', 'Vocabulary'), ('Grammar', 'Grammar')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='test_papers', to='questions.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
