# Generated by Django 5.2.5 on 2025-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='level_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
