# Generated by Django 5.2.5 on 2025-09-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpaper', '0002_testpaper_level_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='pass_percentage',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
